Fetch dhcp sent ntp server ips & set eth intf obj
ibm-openbmc/phosphor-networkd pull request #21
Opened 2022-01-06 11:14 UTC by asmithakarun

Currently, whenever thd dhcp sends the ntp server ip
list, the networkd dbus object is not updated with
the same, also the config file is not updated.

The ntp server details are available in the dbus object
hosted by systemd-timesyncd service.

busctl introspect org.freedesktop.timesync1 /org/freedesktop/timesync1
NAME                                TYPE      SIGNATURE          RESULT/VALUE                             FLAGS
org.freedesktop.timesync1.Manager   interface -                  -                                        -
.FallbackNTPServers                 property  as                 4 "time1.google.com" "time2.google.com"… const
.Frequency                          property  x                  0                                        -
.LinkNTPServers                     property  as                 0                                        -
.NTPMessage                         property  (uuuuittayttttbtt) 0 0 0 0 0 0 0 4 0 0 0 0 0 1844453508490… emits-change
.PollIntervalMaxUSec                property  t                  2048000000                               const
.PollIntervalMinUSec                property  t                  32000000                                 const
.PollIntervalUSec                   property  t                  2048000000                               -
.RootDistanceMaxUSec                property  t                  5000000                                  const
.ServerAddress                      property  (iay)              2 4 1 1 1 1                              -
.ServerName                         property  s                  "1.1.1.1"                                -
.SystemNTPServers                   property  as                 0                                        const

In this change, networkd fetches the ntp server details from the
above dbus object, set them in the ethernet interface dbus object and
update the config file (steps are mentioned below in Tested By section).

Tested By:

* Change the ntp server ips in dhcp config file & restart dhcpd
* timesyncd dbus object contains the new list of ips as below:

busctl introspect org.freedesktop.timesync1 /org/freedesktop/timesync1
NAME                                TYPE      SIGNATURE          RESULT/VALUE                             FLAGS
org.freedesktop.DBus.Introspectable interface -                  -                                        -
.Introspect                         method    -                  s                                        -
org.freedesktop.DBus.Peer           interface -                  -                                        -
.GetMachineId                       method    -                  s                                        -
.Ping                               method    -                  -                                        -
org.freedesktop.DBus.Properties     interface -                  -                                        -
.Get                                method    ss                 v                                        -
.GetAll                             method    s                  a{sv}                                    -
.Set                                method    ssv                -                                        -
.PropertiesChanged                  signal    sa{sv}as           -                                        -
org.freedesktop.timesync1.Manager   interface -                  -                                        -
.FallbackNTPServers                 property  as                 4 "time1.google.com" "time2.google.com"… const
.Frequency                          property  x                  0                                        -
.LinkNTPServers                     property  as                 1 "1.1.1.1"                              -
.NTPMessage                         property  (uuuuittayttttbtt) 0 0 0 0 0 0 0 4 0 0 0 0 0 1844453508490… emits-change
.PollIntervalMaxUSec                property  t                  2048000000                               const
.PollIntervalMinUSec                property  t                  32000000                                 const
.PollIntervalUSec                   property  t                  2048000000                               -
.RootDistanceMaxUSec                property  t                  5000000                                  const
.ServerAddress                      property  (iay)              2 4 1 1 1 1                              -
.ServerName                         property  s                  "1.1.1.1"                                -
.SystemNTPServers                   property  as                 0                                        const

* networkd restarts since network configuration has changed and during restart
ntp server details are loaded from timesyncd dbus object and set in dbus objects
hosted by networkd as shown below:

busctl introspect xyz.openbmc_project.Network /xyz/openbmc_project/network/eth0
NAME                                              TYPE      SIGNATURE RESULT/VALUE                             FLAGS
org.freedesktop.DBus.Introspectable               interface -         -                                        -
.Introspect                                       method    -         s                                        -
org.freedesktop.DBus.Peer                         interface -         -                                        -
.GetMachineId                                     method    -         s                                        -
.Ping                                             method    -         -                                        -
org.freedesktop.DBus.Properties                   interface -         -                                        -
.Get                                              method    ss        v                                        -
.GetAll                                           method    s         a{sv}                                    -
.Set                                              method    ssv       -                                        -
.PropertiesChanged                                signal    sa{sv}as  -                                        -
xyz.openbmc_project.Collection.DeleteAll          interface -         -                                        -
.DeleteAll                                        method    -         -                                        -
xyz.openbmc_project.Network.EthernetInterface     interface -         -                                        -
.AutoNeg                                          property  b         false                                    emits-change writable
.DHCPEnabled                                      property  s         "xyz.openbmc_project.Network.EthernetIn… emits-change writable
.DefaultGateway                                   property  s         "x.x.x.x"                                emits-change writable
.DefaultGateway6                                  property  s         ""                                       emits-change writable
.DomainName                                       property  as        0                                        emits-change writable
.IPv6AcceptRA                                     property  b         true                                     emits-change writable
.InterfaceName                                    property  s         "eth0"                                   emits-change writable
.LinkLocalAutoConf                                property  s         "xyz.openbmc_project.Network.EthernetIn… emits-change writable
.LinkUp                                           property  b         true                                     const
.MTU                                              property  u         1500                                     emits-change writable
.NICEnabled                                       property  b         true                                     emits-change wri [...]

2022-01-07 05:09 UTC, sunharis requested changes
Posted some comments upstream. Please pull them here.

2022-01-10 15:44 UTC, sunharis approved these changes
Looks good. Please edit the commit message here as well - to make it a bit shorter

2022-01-19 12:17 UTC, raviteja-b commented
Each Ethernet interface has NTPServers property and one ethernet interface can have static IP config and another interface can have DHCP enabled.
so DHCP provided NTP servers applies to specific interface 
How do we differentiate and populate NTP servers specific to each interfaces?

busctl introspect xyz.openbmc_project.Network /xyz/openbmc_project/network/eth0                                 
.NTPServers                                       property  as        0

2022-01-26 19:10 UTC, gtmills commented
Upstream has a -1 from a maintainer, can we address Ratan's feedback, keep going upstream a bit to ensure we are headed in the correct direction before we merge this ?

2022-04-14 08:59 UTC, asmithakarun commented
Created a new PR with these changes, since this fork doesnt contain the latest 1020 changes, and gerrit commit had a few more changes on top of it:
https://github.com/ibm-openbmc/phosphor-networkd/pull/34

2022-04-14 08:59 UTC, closed without merging