Update dbus w.r.t bios settings patch req
ibm-openbmc/phosphor-networkd pull request #22
Opened 2022-01-25 19:21 UTC by asmithakarun

When a user fires a redfish patch request on bios settings to
change the ipv4 method to static/dhcp, the same is updated in the
bios table. But the hypervisor eth dbus object does not listen to
this property change signal in biostable and hence, it does not change
the DHCPEnabled property on the hypervisor eth object.
This causes wrong data to be sent in the redfish response.

This PR has the change to listen to that property change in bios
table and synchronizes the hypervisor dbus object.

This fixes: https://w3.rchland.ibm.com/projects/bestquest/?verb=view&id=SW541539

Tested By:

- Tested on a system where:
  * eth0 & eth1 are connected to a dhcp server each
  * only eth1 is connected to dhcp server

1. eth0:

PATCH -d '{"Attributes": {"vmi_if0_ipv4_method": "IPv4Static"}}' https://$bmc/redfish/v1/Systems/system/Bios/Settings

GET https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth0{
  "@odata.id": "/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth0",
  "@odata.type": "#EthernetInterface.v1_5_1.EthernetInterface",
  "DHCPv4": {
    "DHCPEnabled": false
  },
  "Description": "Hypervisor's Virtual Management Ethernet Interface",
  "HostName": "",
  "IPv4Addresses": [],
  "IPv4StaticAddresses": [],
  "Id": "eth0",
  "InterfaceEnabled": true,
  "Name": "Hypervisor Ethernet Interface"
}

PATCH -d '{"Attributes": {"vmi_if0_ipv4_method": "IPv4DHCP"}}' https://$bmc/redfish/v1/Systems/system/Bios/Settings

GET https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth0{
  "@odata.id": "/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth0",
  "@odata.type": "#EthernetInterface.v1_5_1.EthernetInterface",
  "DHCPv4": {
    "DHCPEnabled": true
  },
  "Description": "Hypervisor's Virtual Management Ethernet Interface",
  "HostName": "",
  "IPv4Addresses": [
    {
      "Address": "192.168.1.39",
      "AddressOrigin": "DHCP",
      "Gateway": "192.168.1.1",
      "SubnetMask": "255.255.255.0"
    }
  ],
  "IPv4StaticAddresses": [],
  "Id": "eth0",
  "InterfaceEnabled": true,
  "Name": "Hypervisor Ethernet Interface"
}

2. eth1:

PATCH -d '{"Attributes": {"vmi_if1_ipv4_method": "IPv4Static"}}' https://$bmc/redfish/v1/Systems/system/Bios/Settings

GET https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth1
{
  "@odata.id": "/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth1",
  "@odata.type": "#EthernetInterface.v1_5_1.EthernetInterface",
  "DHCPv4": {
    "DHCPEnabled": false
  },
  "Description": "Hypervisor's Virtual Management Ethernet Interface",
  "HostName": "",
  "IPv4Addresses": [],
  "IPv4StaticAddresses": [],
  "Id": "eth1",
  "InterfaceEnabled": true,
  "Name": "Hypervisor Ethernet Interface"
}

PATCH -d '{"Attributes": {"vmi_if1_ipv4_method": "IPv4DHCP"}}' https://$bmc/redfish/v1/Systems/system/Bios/Settings

GET https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth1
{
  "@odata.id": "/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth1",
  "@odata.type": "#EthernetInterface.v1_5_1.EthernetInterface",
  "DHCPv4": {
    "DHCPEnabled": true
  },
  "Description": "Hypervisor's Virtual Management Ethernet Interface",
  "HostName": "",
  "IPv4Addresses": [
    {
      "Address": "192.168.1.30",
      "AddressOrigin": "DHCP",
      "Gateway": "192.168.1.1",
      "SubnetMask": "255.255.255.0"
    }
  ],
  "IPv4StaticAddresses": [],
  "Id": "eth1",
  "InterfaceEnabled": true,
  "Name": "Hypervisor Ethernet Interface"
}

Also cross-checked with the dollowing command, and it seems to work as expected:
* PATCH -d '{"DHCPv4": {"DHCPEnabled" :<false/true>}}' https://$bmc/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth<0/1>

Signed-off-by: Asmitha Karunanithi <asmitk01@in.ibm.com>

2022-01-27 04:36 UTC, sunharis requested changes
Please remove the outputs of the commands which are captured in the commit message.  Just listing the commands used to test the changes is good enough.
Is it possible to print the ip address value in the traces which is getting updated? This will give more data for debug

2022-01-27 05:00 UTC, raviteja-b approved these changes

2022-01-28 13:47 UTC, asmithakarun commented
> Please remove the outputs of the commands which are captured in the commit message. Just listing the commands used to test the changes is good enough.
> Is it possible to print the ip address value in the traces which is getting updated? This will give more data for debug

done

2022-01-29 03:45 UTC, sunharis approved these changes

2022-01-31 22:08 UTC, merged