Duplicate entries getting created for static DNS.
ibm-openbmc/phosphor-networkd pull request #69
Opened 2023-03-28 19:58 UTC by nkotania

Currently, we store the dbus DNS values in a vector that causes duplicate entries and due to those duplicate entries created.

With this commitment, we are going to store static DNS values in a SET rather than a vector to create a unique list of DNS values

Tested By: PATCH -d '{"StaticNameServers":["10.4.5.60", "10.4.5.60"]}'
    https://${bmc_ip}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0

Change-Id: I0c18eb5fec36c4305f1ded4c5e57bbd046ca4576

2023-03-29 04:27 UTC, sunharis requested changes
@nitinkotania the PR should be against 1040 branch.

2023-03-29 04:31 UTC, nkotania commented
> @nitinkotania the PR should be against 1040 branch.

Changed it to 1040 branch.

2023-03-29 04:33 UTC, sunharis approved these changes

2023-03-29 04:33 UTC, sunharis commented
jenkins run tests please

2023-03-29 16:23 UTC, mdmillerii requested changes
Administrators often have primary and backup name server.   Depending on client history and the policy for sending the request reordering the name Servers can result in degraded service (eg using a server farther away). 

Also redfish patch sematic requires order to be preserved.

2023-04-04 08:43 UTC, nkotania commented
Created a new PR: https://github.com/ibm-openbmc/phosphor-networkd/pull/77 for 1050 driver

2023-04-04 09:19 UTC, nkotania commented
> Administrators often have primary and backup name server. Depending on client history and the policy for sending the request reordering the name Servers can result in degraded service (eg using a server farther away).
> 
> Also redfish patch sematic requires order to be preserved.

Modified the code and now the order is not changing, create a new PR : https://github.com/ibm-openbmc/phosphor-networkd/pull/78

2023-04-04 09:20 UTC, nkotania commented
Created a new PR: https://github.com/ibm-openbmc/phosphor-networkd/pull/78

2023-04-04 09:20 UTC, closed without merging